### ISSUE TITLE
error: cannot find -lxilinxopencl and -llmx6.0

### ISSUE THREAD

**Issue by MacmillanZhu** [dicecco1/fpga_caffe#15]
Hi, thanks for open-sourcing. I try to compile and run this, after "make all", I got an error bellow:

> LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: cannot find -lxilinxopencl
/usr/bin/ld: cannot find -llmx6.0
collect2: error: ld returned 1 exit status
Makefile:608: recipe for target '.build_release/lib/libcaffe.so.1.0.0' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1

According to your reply in issue #5, I sourced the settings64.sh file, but the error still exists.
By the way, I'm using SDAccel 2017.1 on Ubuntu 16.04.5 LTS Version.
Any suggestions?

**Comment by Nyceane** [comment]
I am having same problem, can someone help?

**Comment by carherlu** [comment]
I'm also having the same problem

**Comment by louvinci** [comment]
God... Has the problem been solved?

**Comment by dicecco1** [comment]
I'm no longer actively working on this project, the issue is most likely due to some change in the build flow with other versions of SDAccel/OS combinations so it'd probably just involve tinkering with the Makefile a bit to get everything compiling again

**Comment by louvinci** [comment]
Thank you for your reply. I'll have a try.

**Comment by louvinci** [comment]
> I'm no longer actively working on this project, the issue is most likely due to some change in the build flow with other versions of SDAccel/OS combinations so it'd probably just involve tinkering with the Makefile a bit to get everything compiling again

Thank you for your reply. I'll have a try.
